name: app_nation_case
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

  #state management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  #network
  dio: ^5.8.0+1
  internet_connection_checker: ^3.0.1

  #local
  path_provider: ^2.1.5

  #di
  get_it: ^8.0.3

  url_launcher: ^6.3.1 
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/

  fonts:
  - family: GalanoGrotesque
    fonts:
      - asset: assets/fonts/GalanoGrotesque-Medium.ttf
        weight: 500
      - asset: assets/fonts/GalanoGrotesque-SemiBold.ttf
        weight: 600

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_icon.png"
  min_sdk_android: 21 